<?php

/*  
 * Implementation of hook_menu()  
 */  
function cg_core_menu(){  
    // desired path location: http://www.oursite.com/our/form  
    $items['admin/config/system/cg_settings'] = array(  
        // page title  
        'title' => 'Homepage Settings',  
        // describe the page for the menu system.  site visitors will not see this  
        'description' => 'Staff configurable page with custom settings form.',  
        // function that is called when visiting the new path to generate the page's content  
        'page callback' => 'cg_core_settings_form',  
        // permissions required to view page  
        'access arguments' => array('administer site configuration'),  
    );  
    return $items;  
}  

/**  
 * Page callback: Custom settings form  
 */  
function cg_core_settings_form($form, &$form_state) {  
  $form['my_custom_blocks1'] = array(  
    '#type' => 'textarea',  
    '#title' => t('Block 1'),  
    '#default_value' => variable_get('mycustom_blocks', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The content inside Block 1'),  
    '#required' => TRUE,  
  );  

  $form['my_custom_blocks2'] = array(  
    '#type' => 'textarea',  
    '#title' => t('Block 2'),  
    '#default_value' => variable_get('mycustom_blocks', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The content inside Block 2'),  
    '#required' => TRUE,  
  );  

  $form['my_custom_blocks3'] = array(  
    '#type' => 'textarea',  
    '#title' => t('Block 3'),  
    '#default_value' => variable_get('my_custom_blocks', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The content inside Block 3'),  
    '#required' => TRUE,  
  );    

  return system_settings_form($form);  
}  