<?php

/*  
 * Implementation of hook_menu()  
 */  
function cg_core_menu(){  
    // desired path location: http://www.oursite.com/our/form  
    $items['admin/config/system/cg_settings'] = array(  
        // page title  
        'title' => 'Homepage Settings',  
        // describe the page for the menu system.  site visitors will not see this  
        'description' => 'Staff configurable page with custom settings form.',  
        // function that is called when visiting the new path to generate the page's content  
        'page callback' => 'cg_core_settings_form',  
        // permissions required to view page  
        'access arguments' => array('administer site configuration'),  
    );  
    return $items;  
}  

/**  
 * Page callback: Custom settings form  
 */  
function cg_core_settings_form($form, &$form_state) {  
  $form['cgc_title_1'] = array(  
    '#type' => 'textfield',  
    '#title' => t('Block 1 title'),  
    '#default_value' => variable_get('cgc_title_1', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The title of Block 1'),  
    '#required' => TRUE,  
  );  

  $form['cgc_block_1'] = array(  
    '#type' => 'textarea',  
    '#title' => t('Block 1'),  
    '#default_value' => variable_get('cgc_block_1', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The content inside Block 1'),  
    '#required' => TRUE,  
  );

  $form['cgc_title_2'] = array(  
    '#type' => 'textfield',  
    '#title' => t('Block 2 title'),  
    '#default_value' => variable_get('cgc_title_2', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The title of Block 2'),  
    '#required' => TRUE,  
  );    

  $form['cgc_block_2'] = array(  
    '#type' => 'textarea',  
    '#title' => t('Block 2'),  
    '#default_value' => variable_get('cgc_block_2', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The content inside Block 2'),  
    '#required' => TRUE,  
  );  

    $form['cgc_title_3'] = array(  
    '#type' => 'textfield',  
    '#title' => t('Block 3 title'),  
    '#default_value' => variable_get('cgc_title_3', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The title of Block 3'),  
    '#required' => TRUE,  
  ); 

  $form['cgc_block_3'] = array(  
    '#type' => 'textarea',  
    '#title' => t('Block 3'),  
    '#default_value' => variable_get('cgc_block_3', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The content inside Block 3'),  
    '#required' => TRUE,  
  );    

  $form['cgc_title_4'] = array(  
    '#type' => 'textfield',  
    '#title' => t('Block 4 title'),  
    '#default_value' => variable_get('cgc_title_4', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The title of Block 4'),  
    '#required' => TRUE,  
  );   

  $form['cgc_block_4'] = array(  
    '#type' => 'textarea',  
    '#title' => t('Block 4'),  
    '#default_value' => variable_get('cgc_block_4', 'Welcome to our site'),  
    '#size' => 50,  
    '#maxlength' => 200,  
    '#description' => t('The content inside Block 4'),  
    '#required' => TRUE,  
  );  

  return system_settings_form($form);  
}  
